version: "3"
services:
  github_listener:
    build: .
    container_name: github_retriever
    environment:
      BROKERS: "${BROKERS}"
      INPUT_TOPIC: "${INPUT_TOPIC}"
      OUTPUT_TOPIC: "${OUTPUT_TOPIC}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      CONSUMER_CONFIG: "${CONSUMER_CONFIG}"
      PRODUCER_CONFIG: "${PRODUCER_CONFIG}"
    volumes:
      - ./githubListener/app:/bytewax/app
    command: ["python", "-m", "bytewax.run", "-w4", "dataflows/github_commit_processing"]

  commit_summary_service:
    build: .
    container_name: commit_summary_service
    environment:
      BROKERS: "${BROKERS}"
      OUTPUT_TOPIC: "${OUTPUT_TOPIC}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      PROCESSED_TOPIC: "${PROCESSED_TOPIC}"
      CONSUMER_CONFIG: "${CONSUMER_CONFIG}"
      PRODUCER_CONFIG: "${PRODUCER_CONFIG}"
      TEMPLATE: "${TEMPLATE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - ./commit_summary_service/app:/bytewax/app  # Adjust to match the working directory
    command: ["python", "-m", "bytewax.run", "-w4", "dataflows/commit_summary_service"]
