version: "3"
services:
  github_listener:
    build: .
    container_name: github_retriever
    environment:
      BROKERS: "${BROKERS}"
      INPUT_TOPIC: "${INPUT_TOPIC}"
      OUTPUT_TOPIC: "${OUTPUT_TOPIC}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      CONSUMER_CONFIG: "${CONSUMER_CONFIG}"
      PRODUCER_CONFIG: "${PRODUCER_CONFIG}"
    volumes:
      - ./githubListener/app:/bytewax/app
      - ./recovery/github_listener:/bytewax/recovery/github_listener
    command: ["python", "-m", "bytewax.run", "-r", "/bytewax/recovery/github_listener", "-s", "300", "-b", "600", "-w4", "dataflows/github_commit_processing"]

  commit_summary_service:
    build: .
    container_name: commit_summary_service
    environment:
      BROKERS: "${BROKERS}"
      OUTPUT_TOPIC: "${OUTPUT_TOPIC}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      PROCESSED_TOPIC: "${PROCESSED_TOPIC}"
      CONSUMER_CONFIG: "${CONSUMER_CONFIG}"
      PRODUCER_CONFIG: "${PRODUCER_CONFIG}"
      TEMPLATE: "${TEMPLATE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - ./commit_summary_service/app:/bytewax/app
      - ./recovery/commit_summary_service:/bytewax/recovery/commit_summary_service
    command: ["python", "-m", "bytewax.run", "-r", "/bytewax/recovery/commit_summary_service", "-s", "300", "-b", "600", "-w4", "dataflows/commit_summary_service"]

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage:z

  add_qdrant_service:
    build: .
    container_name: add_qdrant_service
    environment:
      BROKERS: "${BROKERS}"
      OUTPUT_TOPIC: "${OUTPUT_TOPIC}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      PROCESSED_TOPIC: "${PROCESSED_TOPIC}"
      CONSUMER_CONFIG: "${CONSUMER_CONFIG}"
      PRODUCER_CONFIG: "${PRODUCER_CONFIG}"
      TEMPLATE: "${TEMPLATE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - ./add_qdrant_service/app:/bytewax/app
      - ./recovery/add_qdrant_service:/bytewax/recovery/add_qdrant_service
    command: ["python", "-m", "bytewax.run", "-r", "/bytewax/recovery/add_qdrant_service", "-s", "300", "-b", "600", "-w4", "dataflows/add_qdrant_service"]

volumes:
  qdrant-storage:
