name: "PDF Processing Intergration Test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - "6333:6333"
          - "6334:6334"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Kafka KRaft Broker
        uses: spicyparrot/kafka-kraft-action@v1.1.0
        with:
          kafka-version: "3.7.0"
          kafka-topics: "repos-topic,1,github-commits-out,1,addtovectordb,1,QdrantOutput,1,pdfInput,1"

      - name: Set environment variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.TOKEN_GITHUB }}" >> $GITHUB_ENV
          echo "BROKERS=${{ env.kafka_runner_address }}:9093" >> $GITHUB_ENV
          echo "INPUT_TOPIC=repos-topic" >> $GITHUB_ENV
          echo "OUTPUT_TOPIC=github-commits-out" >> $GITHUB_ENV
          echo "CONSUMER_CONFIG={\"bootstrap.servers\": \"${{ env.kafka_runner_address }}:9093\",\"group.id\": \"your_unique_group_id\",\"auto.offset.reset\": \"latest\",\"enable.auto.commit\": \"true\"}" >> $GITHUB_ENV
          echo "PRODUCER_CONFIG={\"bootstrap.servers\": \"${{ env.kafka_runner_address }}:9093\"}" >> $GITHUB_ENV
          echo "PROCESSED_TOPIC=addtovectordb" >> $GITHUB_ENV
          echo "VECTORDB_TOPIC_NAME="QdrantOutput"" >> $GITHUB_ENV
          echo "MODEL_PROVIDER=fake" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=sk-fakekeyapikey" >> $GITHUB_ENV
          echo "TEMPLATE=${{ secrets.TEMPLATE }}" >> $GITHUB_ENV
          echo "VECTOR_DB_HOST=localhost" >> $GITHUB_ENV
          echo "LOCAL_LLM_URL=localhost" >> $GITHUB_ENV
          echo "PDF_INPUT=pdfInput" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Run PDF Processing Intergration Test
        run: pytest tests/test_kafka_pdf.py
